name = "CreateNeoForge"
author = "Jerryx77"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2983f12adcedcd83e8fb29ce90731c478863c57600f4c8b6e7f7c58b293e4bd9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
