name = "CreateForge"
author = "Jerryx77"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6dd3cc631d9fe3d792695c1e8c1a85c04eec5e18fe26cdf2a5fca15c8b127be"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
